package examples:aggregate-with-state;
interface aggregate-with-state-service {
    aggregate-fn: func() -> result<list<string>,string>;

    init-my-state: func( value: my-state);

    use sdf:df/lazy.{ df-value };
    type my-state = df-value;
}
world aggregate-with-state-world {
    export aggregate-with-state-service;
}

