package examples:multi-state;
interface multi-state-service {
    multi-state-fn: func(input: string) -> result<string,string>;
    use sdf:row-state/row.{ row-value };
    init-count-per-word-row: func( value: row-value);

    record count-per-word-row-item-value {
      count: s32,
      last-match: string,
    }

    use sdf:value-state/values.{ value32 };
    init-count-per-word-scalar: func( value: value32 );

}
world multi-state-world {
    export multi-state-service;
}
