package examples:row-state;
interface row-state-service {
    row-state-fn: func(input: string) -> result<_,string>;
    use sdf:row-state/row.{ row-value };
    init-count-per-word-row: func( value: row-value);

    record count-per-word-row-item-value {
      count: s32,
      last-match: string,
    }
}
world row-state-world {
    export row-state-service;
}
