[package]
name = "source_cars"
version = "0.0.0"
edition = "2021"
description = ""

[lib]
crate-type = ["cdylib"]


[dependencies]
serde = { workspace = true }
wit-bindgen = { workspace = true, features = ["macros"]}
serde_json = { workspace = true }
simd-json = { workspace = true }